baseURL = "https://blog.border.cash/"
languageCode = "en-us"
title = "BorderCash Blog"
theme = "PaperMod"
googleAnalytics = "G-4EVNSKVCMW"

[params]
  ShowSearch = true
  defaultTheme = "light"

  [params.assets]
  favicon = "images/favicon.ico"

  
  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Money and Plugs, Links, about..."

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/thebordercash"

 

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/border.cash"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/company/bordercash"

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON is needed for search

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "https://border.cash"
  weight = 1


[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  identifier = "app"
  name = "App"
  url = "https://app.border.cash"
  weight = 3

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "https://border.cash/contact/"
  weight = 4
