baseURL = "https://blog.border.cash/"
languageCode = "en-us"
title = "BorderCash Blog"
theme = "PaperMod"


[params]
  ShowSearch = true
  defaultTheme = "light" 

  favicon = "pluggedspace.png"

  title = "BorderCash Blog"
  description = "Your blog description here"
  author = "BorderCash"
  keywords = ["fintech", "tokenized stocks", "cross-border"]
  images = ["your-featured-image-url.jpg"]
  disableSpecial1stPost = true
  disableScrollToTop = false
  disableShare = false

  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true

  googleAnalyticsID = "G-HNJ4XDXZ6C"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Sockets and Plugs, Links, about..."

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/thebordercash"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/pluggedspace"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/border.cash"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/company/bordercash"



[params.opengraph]
  twitter_cards = true
  facebook = true

[params.seo]
  hideMetadata = false

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON is needed for search

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "https://border.cash"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "https://pluggedspace.org/about"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "https://blog.border.cash"
  weight = 3

 [[menu.main]]
  identifier = "services"
  name = "Services"
  url = "https://pluggedspace.org/services"
  weight = 4

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "https://pluggedspace.org/projects"
  weight = 5

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "https://pluggedspace.org/contact/"
  weight = 6




  
